import { IncomingWebhookDefaultArguments } from '@slack/webhook';

export const slackOptions: IncomingWebhookDefaultArguments = {
  channel: '#general',
  username: 'AWS Lambda',
  icon_emoji: ':aws:',
};

export const serviceAliases = {
  Total: '合計',
  'AWS Backup': 'Backup',
  'AWS CloudTrail': 'CloudTrail',
  'AWS Direct Connect': 'DirectConnect',
  'AWS Key Management Service': 'KMS',
  'AWS Lambda': 'Lambda',
  'Amazon CloudFront': 'CloudFront',
  'AWS Config': 'Config',
  'Amazon EC2 Container Registry (ECR)': 'ECR',
  'Amazon EC2 Container Service': 'ECS',
  'Amazon ElastiCache': 'ElastiCache',
  'EC2 - Other': 'NATGateway',
  'Amazon Elastic Compute Cloud - Compute': 'EC2',
  'Amazon GuardDuty': 'GuardDuty',
  'Amazon Elastic Load Balancing': 'ALB/ELB',
  'Amazon Elasticsearch Service': 'ES',
  'Amazon Elastic File System': 'EFS',
  'Amazon Relational Database Service': 'RDS',
  'Amazon Route 53': 'Route53',
  'Amazon Simple Email Service': 'SES',
  'Amazon Simple Notification Service': 'SNS',
  'Amazon Simple Storage Service': 'S3',
  AmazonCloudWatch: 'CloudWatch',
  'AWS Elemental MediaLive': 'MediaLive',
  'AWS Elemental MediaStore': 'MediaStore',
  'Amazon DynamoDB': 'DynamoDB',
  'Amazon Elastic Transcoder': 'ElasticTranscoder',
  'AWS Elemental MediaConvert': 'MediaConvert',
  'Amazon Simple Queue Service': 'SQS',
  Tax: '税金',
} as const;

export const serviceEmoji: Record<keyof typeof serviceAliases, string> = {
  Total: ':money_with_wings:',
  'AWS Backup': ':luggage:',
  'AWS CloudTrail': ':aws-cloudwatch:',
  'AWS Direct Connect': ':handshake:',
  'AWS Key Management Service': ':key:',
  'AWS Lambda': ':lambda:',
  'Amazon CloudFront': ':lightning:',
  'AWS Config': ':eyes:',
  'Amazon EC2 Container Registry (ECR)': ':docker:',
  'Amazon EC2 Container Service': ':aws_ecs:',
  'Amazon ElastiCache': ':redis:',
  'EC2 - Other': ':aws-es:',
  'Amazon Elastic Compute Cloud - Compute': ':linux_penguin:',
  'Amazon GuardDuty': ':cop:',
  'Amazon Elastic Load Balancing': ':scales:',
  'Amazon Elasticsearch Service': ':elasticsearch:',
  'Amazon Elastic File System': ':file_folder:',
  'Amazon Relational Database Service': ':mysql_dolphin:',
  'Amazon Route 53': ':route53:',
  'Amazon Simple Email Service': ':email:',
  'Amazon Simple Notification Service': ':iphone:',
  'Amazon Simple Storage Service': ':card_file_box:',
  AmazonCloudWatch: ':aws-cloudwatch:',
  'AWS Elemental MediaLive': ':movie_camera:',
  'AWS Elemental MediaStore': ':vhs:',
  'Amazon DynamoDB': ':aws-dynamodb:',
  'Amazon Elastic Transcoder': ':film_frames:',
  'AWS Elemental MediaConvert': ':film_frames:',
  'Amazon Simple Queue Service': ':aws_sqs:',
  Tax: ':moneybag:',
} as const;
